language: php
php:
    - 7.1
    - 7.2
    - nightly

env:
    matrix:
        - DEPENDENCIES="high"
        - DEPENDENCIES="low"
    global:
        - DEFAULT_COMPOSER_FLAGS="--no-interaction --no-ansi --no-progress --no-suggest"

before_install:
    # Update composer
    - composer self-update
    - composer clear-cache
    # Install apcu
    - pecl channel-update pecl.php.net
    - echo yes | pecl upgrade apcu

install:
    - if [[ "$DEPENDENCIES" = 'high' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS; fi
    - if [[ "$DEPENDENCIES" = 'low' ]]; then travis_retry composer update $DEFAULT_COMPOSER_FLAGS --prefer-lowest; fi

script:
    - vendor/bin/phpunit --configuration phpunit.xml.dist

notifications:
    email:
        on_failure: change
